import SideBarItem from '../components/Sidebar/SideBarItem'
import Sidebar from '../components/Sidebar/Sidebar'

export default function Home() {
  return (
    <div className='w-full px-8' >
  <div
   className='
   w-full
   pl-28
   sm:pl-52
   md:pl-64
   lg:pl-80
   '
   >
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   <div>a</div>
   </div>
    </div>
 
  )
}
